name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-12']
        swift: ['5.6']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1.14.0
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build
    - name: Test
      run: swift test
