name: Docs

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.7'
    - name: Generate Docs
      uses: fwcd/swift-docc-action@v1
      with:
        target: Discord
        output: ./public
        transform-for-static-hosting: 'true'
        disable-indexing: 'true'
        hosting-base-path: swift-discord
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
