name: Docs

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate Docs
      uses: sersoft-gmbh/swifty-docs-action@v1
      with:
        output: public
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
